// Package Comm comment
// This file was generated by jce2go 2.0.0
// Generated from Position.jce
package Comm

import (
	"fmt"

	"gitlab.upchinaproduct.com/taf/tafgo/taf/protocol/codec"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = codec.FromInt8

// InitReq struct implement
type InitReq struct {
	codec.JceStructBase
	SSuffix string `json:"sSuffix"`
}

func (st *InitReq) ResetDefault() {
	st.JceStructBase.ResetPrecision()
}

// ReadFrom reads  from _is and put into struct.
func (st *InitReq) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.ResetDefault()

	_is.SavePrecision()

	err = _is.Read_string(&st.SSuffix, 1, true)
	if err != nil {
		return err
	}

	st.SetPrecision(_is.ResumePrecision())

	_ = err
	_ = length
	_ = have
	_ = ty
	return nil
}

// ReadBlock reads struct from the given tag , require or optional.
func (st *InitReq) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.ResetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require InitReq, but not exist. tag %d", tag)
		}
		return nil
	}

	err = st.ReadFrom(_is)
	if err != nil {
		return err
	}

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

// WriteTo encode struct to buffer
func (st *InitReq) WriteTo(_os *codec.Buffer) error {
	var err error

	_os.SavePrecision(st.GetPrecision())

	err = _os.Write_string(st.SSuffix, 1)
	if err != nil {
		return err
	}

	_os.ResumePrecision()

	_ = err

	return nil
}

// WriteBlock encode struct
func (st *InitReq) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	err = st.WriteTo(_os)
	if err != nil {
		return err
	}

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}

// Display this struct to a string.
func (st *InitReq) Display() string {
	var ret string
	ret = "{ "
	ret = ret + fmt.Sprint("sSuffix:", st.SSuffix)

	ret = ret + " }"
	return ret
}

// InitRsp struct implement
type InitRsp struct {
	codec.JceStructBase
	SPosition string `json:"sPosition"`
	SMsg      string `json:"sMsg"`
}

func (st *InitRsp) ResetDefault() {
	st.JceStructBase.ResetPrecision()
}

// ReadFrom reads  from _is and put into struct.
func (st *InitRsp) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.ResetDefault()

	_is.SavePrecision()

	err = _is.Read_string(&st.SPosition, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.SMsg, 2, false)
	if err != nil {
		return err
	}

	st.SetPrecision(_is.ResumePrecision())

	_ = err
	_ = length
	_ = have
	_ = ty
	return nil
}

// ReadBlock reads struct from the given tag , require or optional.
func (st *InitRsp) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.ResetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require InitRsp, but not exist. tag %d", tag)
		}
		return nil
	}

	err = st.ReadFrom(_is)
	if err != nil {
		return err
	}

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

// WriteTo encode struct to buffer
func (st *InitRsp) WriteTo(_os *codec.Buffer) error {
	var err error

	_os.SavePrecision(st.GetPrecision())

	err = _os.Write_string(st.SPosition, 1)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.SMsg, 2)
	if err != nil {
		return err
	}

	_os.ResumePrecision()

	_ = err

	return nil
}

// WriteBlock encode struct
func (st *InitRsp) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	err = st.WriteTo(_os)
	if err != nil {
		return err
	}

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}

// Display this struct to a string.
func (st *InitRsp) Display() string {
	var ret string
	ret = "{ "
	ret = ret + fmt.Sprint("sPosition:", st.SPosition)
	ret = ret + ",  "
	ret = ret + fmt.Sprint("sMsg:", st.SMsg)

	ret = ret + " }"
	return ret
}

// OneSideReq struct implement
type OneSideReq struct {
	codec.JceStructBase
	SSrcPosition string `json:"sSrcPosition"`
	SSuffix      string `json:"sSuffix"`
}

func (st *OneSideReq) ResetDefault() {
	st.JceStructBase.ResetPrecision()
}

// ReadFrom reads  from _is and put into struct.
func (st *OneSideReq) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.ResetDefault()

	_is.SavePrecision()

	err = _is.Read_string(&st.SSrcPosition, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.SSuffix, 2, true)
	if err != nil {
		return err
	}

	st.SetPrecision(_is.ResumePrecision())

	_ = err
	_ = length
	_ = have
	_ = ty
	return nil
}

// ReadBlock reads struct from the given tag , require or optional.
func (st *OneSideReq) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.ResetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require OneSideReq, but not exist. tag %d", tag)
		}
		return nil
	}

	err = st.ReadFrom(_is)
	if err != nil {
		return err
	}

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

// WriteTo encode struct to buffer
func (st *OneSideReq) WriteTo(_os *codec.Buffer) error {
	var err error

	_os.SavePrecision(st.GetPrecision())

	err = _os.Write_string(st.SSrcPosition, 1)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.SSuffix, 2)
	if err != nil {
		return err
	}

	_os.ResumePrecision()

	_ = err

	return nil
}

// WriteBlock encode struct
func (st *OneSideReq) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	err = st.WriteTo(_os)
	if err != nil {
		return err
	}

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}

// Display this struct to a string.
func (st *OneSideReq) Display() string {
	var ret string
	ret = "{ "
	ret = ret + fmt.Sprint("sSrcPosition:", st.SSrcPosition)
	ret = ret + ",  "
	ret = ret + fmt.Sprint("sSuffix:", st.SSuffix)

	ret = ret + " }"
	return ret
}

// OneSideRsp struct implement
type OneSideRsp struct {
	codec.JceStructBase
	STargetPosition string `json:"sTargetPosition"`
	SMsg            string `json:"sMsg"`
}

func (st *OneSideRsp) ResetDefault() {
	st.JceStructBase.ResetPrecision()
}

// ReadFrom reads  from _is and put into struct.
func (st *OneSideRsp) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.ResetDefault()

	_is.SavePrecision()

	err = _is.Read_string(&st.STargetPosition, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.SMsg, 2, false)
	if err != nil {
		return err
	}

	st.SetPrecision(_is.ResumePrecision())

	_ = err
	_ = length
	_ = have
	_ = ty
	return nil
}

// ReadBlock reads struct from the given tag , require or optional.
func (st *OneSideRsp) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.ResetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require OneSideRsp, but not exist. tag %d", tag)
		}
		return nil
	}

	err = st.ReadFrom(_is)
	if err != nil {
		return err
	}

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

// WriteTo encode struct to buffer
func (st *OneSideRsp) WriteTo(_os *codec.Buffer) error {
	var err error

	_os.SavePrecision(st.GetPrecision())

	err = _os.Write_string(st.STargetPosition, 1)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.SMsg, 2)
	if err != nil {
		return err
	}

	_os.ResumePrecision()

	_ = err

	return nil
}

// WriteBlock encode struct
func (st *OneSideRsp) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	err = st.WriteTo(_os)
	if err != nil {
		return err
	}

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}

// Display this struct to a string.
func (st *OneSideRsp) Display() string {
	var ret string
	ret = "{ "
	ret = ret + fmt.Sprint("sTargetPosition:", st.STargetPosition)
	ret = ret + ",  "
	ret = ret + fmt.Sprint("sMsg:", st.SMsg)

	ret = ret + " }"
	return ret
}

// BetweenReq struct implement
type BetweenReq struct {
	codec.JceStructBase
	SLeftPosition  string `json:"sLeftPosition"`
	SRightPosition string `json:"sRightPosition"`
	SSuffix        string `json:"sSuffix"`
}

func (st *BetweenReq) ResetDefault() {
	st.JceStructBase.ResetPrecision()
}

// ReadFrom reads  from _is and put into struct.
func (st *BetweenReq) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.ResetDefault()

	_is.SavePrecision()

	err = _is.Read_string(&st.SLeftPosition, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.SRightPosition, 2, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.SSuffix, 3, true)
	if err != nil {
		return err
	}

	st.SetPrecision(_is.ResumePrecision())

	_ = err
	_ = length
	_ = have
	_ = ty
	return nil
}

// ReadBlock reads struct from the given tag , require or optional.
func (st *BetweenReq) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.ResetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require BetweenReq, but not exist. tag %d", tag)
		}
		return nil
	}

	err = st.ReadFrom(_is)
	if err != nil {
		return err
	}

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

// WriteTo encode struct to buffer
func (st *BetweenReq) WriteTo(_os *codec.Buffer) error {
	var err error

	_os.SavePrecision(st.GetPrecision())

	err = _os.Write_string(st.SLeftPosition, 1)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.SRightPosition, 2)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.SSuffix, 3)
	if err != nil {
		return err
	}

	_os.ResumePrecision()

	_ = err

	return nil
}

// WriteBlock encode struct
func (st *BetweenReq) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	err = st.WriteTo(_os)
	if err != nil {
		return err
	}

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}

// Display this struct to a string.
func (st *BetweenReq) Display() string {
	var ret string
	ret = "{ "
	ret = ret + fmt.Sprint("sLeftPosition:", st.SLeftPosition)
	ret = ret + ",  "
	ret = ret + fmt.Sprint("sRightPosition:", st.SRightPosition)
	ret = ret + ",  "
	ret = ret + fmt.Sprint("sSuffix:", st.SSuffix)

	ret = ret + " }"
	return ret
}

// BetweenRsp struct implement
type BetweenRsp struct {
	codec.JceStructBase
	STargetPosition string `json:"sTargetPosition"`
	SMsg            string `json:"sMsg"`
}

func (st *BetweenRsp) ResetDefault() {
	st.JceStructBase.ResetPrecision()
}

// ReadFrom reads  from _is and put into struct.
func (st *BetweenRsp) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.ResetDefault()

	_is.SavePrecision()

	err = _is.Read_string(&st.STargetPosition, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.SMsg, 2, false)
	if err != nil {
		return err
	}

	st.SetPrecision(_is.ResumePrecision())

	_ = err
	_ = length
	_ = have
	_ = ty
	return nil
}

// ReadBlock reads struct from the given tag , require or optional.
func (st *BetweenRsp) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.ResetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require BetweenRsp, but not exist. tag %d", tag)
		}
		return nil
	}

	err = st.ReadFrom(_is)
	if err != nil {
		return err
	}

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

// WriteTo encode struct to buffer
func (st *BetweenRsp) WriteTo(_os *codec.Buffer) error {
	var err error

	_os.SavePrecision(st.GetPrecision())

	err = _os.Write_string(st.STargetPosition, 1)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.SMsg, 2)
	if err != nil {
		return err
	}

	_os.ResumePrecision()

	_ = err

	return nil
}

// WriteBlock encode struct
func (st *BetweenRsp) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	err = st.WriteTo(_os)
	if err != nil {
		return err
	}

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}

// Display this struct to a string.
func (st *BetweenRsp) Display() string {
	var ret string
	ret = "{ "
	ret = ret + fmt.Sprint("sTargetPosition:", st.STargetPosition)
	ret = ret + ",  "
	ret = ret + fmt.Sprint("sMsg:", st.SMsg)

	ret = ret + " }"
	return ret
}
